#!/bin/bash

spinner() {
    local i sp n
    sp='/-\|'
    n=${#sp}
    printf ' '
    while sleep 0.1; do
        printf "%s\b${sp:i++%n:1}"
    done
}

echo 'Automatically fixing sniffed errors'
spinner &

vendor/bin/phpcbf -n --standard=Wordpress-Core --extensions=php --ignore=index.php,resources,vendor,public,node_modules --severity=1 * | tee tests/phpcbf.txt

kill "$!" # kill the spinner
printf '%s\b'

echo 'Fix completed!'
